/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* I2C_scl */
#define I2C_scl_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_scl_0_INBUF_ENABLED 1u
#define I2C_scl_0_INIT_DRIVESTATE 1u
#define I2C_scl_0_INIT_MUXSEL 19u
#define I2C_scl_0_INPUT_SYNC 2u
#define I2C_scl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_scl_0_NUM 0u
#define I2C_scl_0_PORT GPIO_PRT6
#define I2C_scl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_scl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_scl_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_scl_INBUF_ENABLED 1u
#define I2C_scl_INIT_DRIVESTATE 1u
#define I2C_scl_INIT_MUXSEL 19u
#define I2C_scl_INPUT_SYNC 2u
#define I2C_scl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_scl_NUM 0u
#define I2C_scl_PORT GPIO_PRT6
#define I2C_scl_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_scl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_sda */
#define I2C_sda_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_sda_0_INBUF_ENABLED 1u
#define I2C_sda_0_INIT_DRIVESTATE 1u
#define I2C_sda_0_INIT_MUXSEL 19u
#define I2C_sda_0_INPUT_SYNC 2u
#define I2C_sda_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_sda_0_NUM 1u
#define I2C_sda_0_PORT GPIO_PRT6
#define I2C_sda_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_sda_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_sda_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_sda_INBUF_ENABLED 1u
#define I2C_sda_INIT_DRIVESTATE 1u
#define I2C_sda_INIT_MUXSEL 19u
#define I2C_sda_INPUT_SYNC 2u
#define I2C_sda_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_sda_NUM 1u
#define I2C_sda_PORT GPIO_PRT6
#define I2C_sda_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_sda_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT5
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT5
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* MAX_power */
#define MAX_power_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define MAX_power_0_INBUF_ENABLED 0u
#define MAX_power_0_INIT_DRIVESTATE 1u
#define MAX_power_0_INIT_MUXSEL 0u
#define MAX_power_0_INPUT_SYNC 2u
#define MAX_power_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define MAX_power_0_NUM 2u
#define MAX_power_0_PORT GPIO_PRT8
#define MAX_power_0_SLEWRATE CY_GPIO_SLEW_FAST
#define MAX_power_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define MAX_power_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define MAX_power_INBUF_ENABLED 0u
#define MAX_power_INIT_DRIVESTATE 1u
#define MAX_power_INIT_MUXSEL 0u
#define MAX_power_INPUT_SYNC 2u
#define MAX_power_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define MAX_power_NUM 2u
#define MAX_power_PORT GPIO_PRT8
#define MAX_power_SLEWRATE CY_GPIO_SLEW_FAST
#define MAX_power_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_AnyMotion_INT */
#define Pin_AnyMotion_INT_0_DRIVEMODE CY_GPIO_DM_PULLDOWN
#define Pin_AnyMotion_INT_0_INBUF_ENABLED 1u
#define Pin_AnyMotion_INT_0_INIT_DRIVESTATE 0u
#define Pin_AnyMotion_INT_0_INIT_MUXSEL 0u
#define Pin_AnyMotion_INT_0_INPUT_SYNC 2u
#define Pin_AnyMotion_INT_0_INTERRUPT_MODE CY_GPIO_INTR_RISING
#define Pin_AnyMotion_INT_0_NUM 0u
#define Pin_AnyMotion_INT_0_PORT GPIO_PRT13
#define Pin_AnyMotion_INT_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_AnyMotion_INT_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_AnyMotion_INT_DRIVEMODE CY_GPIO_DM_PULLDOWN
#define Pin_AnyMotion_INT_INBUF_ENABLED 1u
#define Pin_AnyMotion_INT_INIT_DRIVESTATE 0u
#define Pin_AnyMotion_INT_INIT_MUXSEL 0u
#define Pin_AnyMotion_INT_INPUT_SYNC 2u
#define Pin_AnyMotion_INT_INTERRUPT_MODE CY_GPIO_INTR_RISING
#define Pin_AnyMotion_INT_NUM 0u
#define Pin_AnyMotion_INT_PORT GPIO_PRT13
#define Pin_AnyMotion_INT_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_AnyMotion_INT_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
